import { METHODS } from 'node:http';
import { Logger } from '@nestjs/common';
import { CORRELATION_ID_HEADER } from '@bible-artisan/contracts';
import { correlationIdOf } from './correlation';

/** The slice of an Express request the access log reads. Deliberately no `url`/`query`/`body`. */
export interface LoggedRequest {
  method: string;
  headers: Record<string, string | string[] | undefined>;
  /** Set by Express once a route matches; its `path` is the route PATTERN, e.g. `/v1/me`. */
  route?: { path?: unknown };
}

/** The slice of an Express response the access log reads. */
export interface LoggedResponse {
  statusCode: number;
  writableFinished: boolean;
  setHeader(name: string, value: string): unknown;
  once(event: 'finish' | 'close', listener: () => void): unknown;
}

/**
 * Every field an access log line may contain (NFR-PRIV-001, PRD §29/§30). This is an allowlist:
 * each value is either generated by the server or drawn from a fixed set, never copied from the
 * request. The raw URL is never logged (it holds IDs and the query string, e.g. a search query);
 * `route` is the matched route pattern from the code instead.
 */
export interface AccessLogFields {
  method: string;
  /** Matched route pattern (`/v1/studies/:studyId`), or `unmatched` when no route handled it. */
  route: string;
  status: number;
  durationMs: number;
  correlationId: string;
  /** Present (true) only when the client went away before the response finished. */
  aborted?: true;
}

const KNOWN_METHODS: ReadonlySet<string> = new Set(METHODS);

/** Route value for requests no route handled: unknown paths, and pre-routing rejections. */
export const UNMATCHED_ROUTE = 'unmatched';

/** A standard HTTP method as-is; anything else collapses to `OTHER`. */
export function loggedMethod(method: string): string {
  return KNOWN_METHODS.has(method) ? method : 'OTHER';
}

/**
 * The matched route's pattern. Nest registers each route on the root Express router with its
 * full path (global prefix included), so `req.route.path` is the whole pattern, always starting
 * with `/`. Everything else logs `unmatched`, never its actual path: requests refused by
 * middleware or the body parser before routing (no `req.route`), and unknown paths, which reach
 * Nest's not-found handler, itself a catch-all route registered as `*path` (no leading slash).
 */
export function routePatternOf(req: LoggedRequest): string {
  const path = req.route?.path;
  return typeof path === 'string' && path.startsWith('/') ? path : UNMATCHED_ROUTE;
}

export function accessLogFields(
  req: LoggedRequest,
  res: LoggedResponse,
  durationMs: number,
  aborted: boolean,
): AccessLogFields {
  return {
    method: loggedMethod(req.method),
    route: routePatternOf(req),
    status: res.statusCode,
    durationMs,
    correlationId: correlationIdOf(req),
    ...(aborted ? { aborted: true as const } : {}),
  };
}

const logger = new Logger('HttpRequest');

/**
 * Express middleware registered FIRST in `configureApp`, ahead of the CSRF/JSON middlewares, the
 * body parsers, guards and handlers, so every /v1 request (including ones those layers refuse)
 * gets its correlation ID before anything can fail, returns it as `X-Correlation-Id`, and emits
 * exactly one access line when the response finishes (or the connection closes first).
 */
export function requestLogging(
  req: LoggedRequest,
  res: LoggedResponse,
  next: (error?: unknown) => void,
): void {
  const startedAt = process.hrtime.bigint();
  res.setHeader(CORRELATION_ID_HEADER, correlationIdOf(req));

  let logged = false;
  const log = (): void => {
    if (logged) return;
    logged = true;
    const durationMs = Number(process.hrtime.bigint() - startedAt) / 1e6;
    const fields = accessLogFields(
      req,
      res,
      Math.round(durationMs * 10) / 10,
      !res.writableFinished,
    );
    logger.log('http_request', fields);
  };
  // `finish` fires once the response is handed to the OS (before the client has read it all), so
  // the line is written by the time a client sees the response. `close` covers aborted requests.
  res.once('finish', log);
  res.once('close', log);
  next();
}
