/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

// No tables yet: the first domain migration lands with BIB-9.
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface DB {}
